# Generated by Django 3.2.2 on 2021-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='seo_title',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
